//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioLematizacion
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reconocimiento", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class Reconocimiento : object
    {
        
        private string FormaCanonicaField;
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        private ServicioLematizacion.InfoCanonica InfoCanonicaField;
        
        private string PalabraField;
        
        private string PrefijosField;
        
        private string PronombresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica
        {
            get
            {
                return this.FormaCanonicaField;
            }
            set
            {
                this.FormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioLematizacion.InfoCanonica InfoCanonica
        {
            get
            {
                return this.InfoCanonicaField;
            }
            set
            {
                this.InfoCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra
        {
            get
            {
                return this.PalabraField;
            }
            set
            {
                this.PalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijos
        {
            get
            {
                return this.PrefijosField;
            }
            set
            {
                this.PrefijosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pronombres
        {
            get
            {
                return this.PronombresField;
            }
            set
            {
                this.PronombresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCanonica", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoCanonica : object
    {
        
        private int AntiguaField;
        
        private int DRAEXXIIIField;
        
        private string FormaCanonicaField;
        
        private int FrecuenciaField;
        
        private int IdCategoriaField;
        
        private int IdCategoriaGNField;
        
        private string IdCategoriaLKField;
        
        private int IdFlexionField;
        
        private int MaxAcepcionesField;
        
        private int MaxEtimologiaField;
        
        private int NumAcepcionField;
        
        private int NumAcepcionSecField;
        
        private int NumEtimologiaField;
        
        private int PosAcepcionField;
        
        private int PosAcepcionSecField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antigua
        {
            get
            {
                return this.AntiguaField;
            }
            set
            {
                this.AntiguaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DRAEXXIII
        {
            get
            {
                return this.DRAEXXIIIField;
            }
            set
            {
                this.DRAEXXIIIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica
        {
            get
            {
                return this.FormaCanonicaField;
            }
            set
            {
                this.FormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaGN
        {
            get
            {
                return this.IdCategoriaGNField;
            }
            set
            {
                this.IdCategoriaGNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoriaLK
        {
            get
            {
                return this.IdCategoriaLKField;
            }
            set
            {
                this.IdCategoriaLKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAcepciones
        {
            get
            {
                return this.MaxAcepcionesField;
            }
            set
            {
                this.MaxAcepcionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxEtimologia
        {
            get
            {
                return this.MaxEtimologiaField;
            }
            set
            {
                this.MaxEtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcion
        {
            get
            {
                return this.NumAcepcionField;
            }
            set
            {
                this.NumAcepcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcionSec
        {
            get
            {
                return this.NumAcepcionSecField;
            }
            set
            {
                this.NumAcepcionSecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtimologia
        {
            get
            {
                return this.NumEtimologiaField;
            }
            set
            {
                this.NumEtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcion
        {
            get
            {
                return this.PosAcepcionField;
            }
            set
            {
                this.PosAcepcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcionSec
        {
            get
            {
                return this.PosAcepcionSecField;
            }
            set
            {
                this.PosAcepcionSecField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamtextFrase", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class ParamtextFrase : object
    {
        
        private string FraseField;
        
        private string IdField;
        
        private List<ServicioLematizacion.ParamtextPalabra> PalabrasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frase
        {
            get
            {
                return this.FraseField;
            }
            set
            {
                this.FraseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ServicioLematizacion.ParamtextPalabra> Palabras
        {
            get
            {
                return this.PalabrasField;
            }
            set
            {
                this.PalabrasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamtextPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class ParamtextPalabra : object
    {
        
        private string FormaCanonicaLKField;
        
        private string IdField;
        
        private string IdCategoriaLKField;
        
        private string IdFraseField;
        
        private string IdParrafoField;
        
        private List<int> InfoMorfoMatchingLKField;
        
        private List<ServicioLematizacion.Reconocimiento> InformacionMorfologicaField;
        
        private string PalabraField;
        
        private string PalabraLKField;
        
        private string PosMarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonicaLK
        {
            get
            {
                return this.FormaCanonicaLKField;
            }
            set
            {
                this.FormaCanonicaLKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoriaLK
        {
            get
            {
                return this.IdCategoriaLKField;
            }
            set
            {
                this.IdCategoriaLKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFrase
        {
            get
            {
                return this.IdFraseField;
            }
            set
            {
                this.IdFraseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdParrafo
        {
            get
            {
                return this.IdParrafoField;
            }
            set
            {
                this.IdParrafoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<int> InfoMorfoMatchingLK
        {
            get
            {
                return this.InfoMorfoMatchingLKField;
            }
            set
            {
                this.InfoMorfoMatchingLKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ServicioLematizacion.Reconocimiento> InformacionMorfologica
        {
            get
            {
                return this.InformacionMorfologicaField;
            }
            set
            {
                this.InformacionMorfologicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra
        {
            get
            {
                return this.PalabraField;
            }
            set
            {
                this.PalabraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalabraLK
        {
            get
            {
                return this.PalabraLKField;
            }
            set
            {
                this.PalabraLKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosMark
        {
            get
            {
                return this.PosMarkField;
            }
            set
            {
                this.PosMarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPalabra : object
    {
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexionador", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoFlexionador : object
    {
        
        private int IdFlexionField;
        
        private string PalabraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra
        {
            get
            {
                return this.PalabraField;
            }
            set
            {
                this.PalabraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVerbo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoVerbo : object
    {
        
        private int FrecuenciaField;
        
        private int IdFlexionField;
        
        private int IdFormaCanonicaField;
        
        private string InfinitivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia
        {
            get
            {
                return this.FrecuenciaField;
            }
            set
            {
                this.FrecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion
        {
            get
            {
                return this.IdFlexionField;
            }
            set
            {
                this.IdFlexionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica
        {
            get
            {
                return this.IdFormaCanonicaField;
            }
            set
            {
                this.IdFormaCanonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Infinitivo
        {
            get
            {
                return this.InfinitivoField;
            }
            set
            {
                this.InfinitivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrimitiva", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPrimitiva : object
    {
        
        private int IdCategoriaField;
        
        private int IdCategoriaPadreField;
        
        private int IdFamiliaField;
        
        private int IdPrefijoField;
        
        private int IdSufijoField;
        
        private string PadreField;
        
        private string PrefijoField;
        
        private bool ReglaPrefijalField;
        
        private bool ReglaSufijalField;
        
        private string SufijoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPadre
        {
            get
            {
                return this.IdCategoriaPadreField;
            }
            set
            {
                this.IdCategoriaPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamilia
        {
            get
            {
                return this.IdFamiliaField;
            }
            set
            {
                this.IdFamiliaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrefijo
        {
            get
            {
                return this.IdPrefijoField;
            }
            set
            {
                this.IdPrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSufijo
        {
            get
            {
                return this.IdSufijoField;
            }
            set
            {
                this.IdSufijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Padre
        {
            get
            {
                return this.PadreField;
            }
            set
            {
                this.PadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaPrefijal
        {
            get
            {
                return this.ReglaPrefijalField;
            }
            set
            {
                this.ReglaPrefijalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaSufijal
        {
            get
            {
                return this.ReglaSufijalField;
            }
            set
            {
                this.ReglaSufijalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo
        {
            get
            {
                return this.SufijoField;
            }
            set
            {
                this.SufijoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrefijo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoPrefijo : object
    {
        
        private int CorteField;
        
        private string EtimologiaField;
        
        private string PrefijoField;
        
        private string PrefijoCanonicoField;
        
        private string SignificadoField;
        
        private string SilabacionField;
        
        private string TipoPrefijoField;
        
        private string VariantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Corte
        {
            get
            {
                return this.CorteField;
            }
            set
            {
                this.CorteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etimologia
        {
            get
            {
                return this.EtimologiaField;
            }
            set
            {
                this.EtimologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefijoCanonico
        {
            get
            {
                return this.PrefijoCanonicoField;
            }
            set
            {
                this.PrefijoCanonicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Significado
        {
            get
            {
                return this.SignificadoField;
            }
            set
            {
                this.SignificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Silabacion
        {
            get
            {
                return this.SilabacionField;
            }
            set
            {
                this.SilabacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPrefijo
        {
            get
            {
                return this.TipoPrefijoField;
            }
            set
            {
                this.TipoPrefijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variantes
        {
            get
            {
                return this.VariantesField;
            }
            set
            {
                this.VariantesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexion", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoFlexion : object
    {
        
        private string FlexionAbrevEnField;
        
        private string FlexionAbrevEsField;
        
        private string FlexionEnField;
        
        private string FlexionEsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEn
        {
            get
            {
                return this.FlexionAbrevEnField;
            }
            set
            {
                this.FlexionAbrevEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEs
        {
            get
            {
                return this.FlexionAbrevEsField;
            }
            set
            {
                this.FlexionAbrevEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEn
        {
            get
            {
                return this.FlexionEnField;
            }
            set
            {
                this.FlexionEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEs
        {
            get
            {
                return this.FlexionEsField;
            }
            set
            {
                this.FlexionEsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCategoria", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    public partial class InfoCategoria : object
    {
        
        private string CategoriaAbrevEnField;
        
        private string CategoriaAbrevEsField;
        
        private string CategoriaEnField;
        
        private string CategoriaEsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaAbrevEn
        {
            get
            {
                return this.CategoriaAbrevEnField;
            }
            set
            {
                this.CategoriaAbrevEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaAbrevEs
        {
            get
            {
                return this.CategoriaAbrevEsField;
            }
            set
            {
                this.CategoriaAbrevEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaEn
        {
            get
            {
                return this.CategoriaEnField;
            }
            set
            {
                this.CategoriaEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaEs
        {
            get
            {
                return this.CategoriaEsField;
            }
            set
            {
                this.CategoriaEsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLematizacion.IServicioLematizacion")]
    public interface IServicioLematizacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/EsVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/EsVerboResponse")]
        bool EsVerbo(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/EsVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/EsVerboResponse")]
        System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/Reconocer", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerResponse")]
        List<ServicioLematizacion.Reconocimiento> Reconocer(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/Reconocer", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrasesResponse")]
        List<ServicioLematizacion.ParamtextFrase> ReconocerTextoPorFrases(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrasesResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.ParamtextFrase>> ReconocerTextoPorFrasesAsync(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerLinguakit", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerLinguakitResponse")]
        List<ServicioLematizacion.ParamtextFrase> ReconocerLinguakit(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerLinguakit", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerLinguakitResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.ParamtextFrase>> ReconocerLinguakitAsync(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFlexible", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFlexibleResponse")]
        List<ServicioLematizacion.Reconocimiento> ReconocerFlexible(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFlexible", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFlexibleResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerVerboResponse")]
        List<ServicioLematizacion.Reconocimiento> ReconocerVerbo(string verbo, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerVerboResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCanonica", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCanonicaResponse")]
        ServicioLematizacion.InfoCanonica ConsultaCanonica(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCanonica", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCanonicaResponse")]
        System.Threading.Tasks.Task<ServicioLematizacion.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPalabra", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPalabraResponse")]
        List<ServicioLematizacion.InfoPalabra> ConsultaPalabra(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPalabra", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPalabraResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPalabra>> ConsultaPalabraAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradas", ReplyAction="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradasResponse")]
        List<string> PalabrasNoEncontradas(List<string> listaPalabras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradas", ReplyAction="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradasResponse")]
        System.Threading.Tasks.Task<List<string>> PalabrasNoEncontradasAsync(List<string> listaPalabras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexionador", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionadorResponse")]
        List<ServicioLematizacion.InfoFlexionador> ConsultaFlexionador(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexionador", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionadorResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaVerboResponse")]
        List<ServicioLematizacion.InfoVerbo> ConsultaVerbo(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaVerboResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.InfoVerbo>> ConsultaVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrimitiva", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrimitivaResponse")]
        List<ServicioLematizacion.InfoPrimitiva> ConsultaPrimitiva(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrimitiva", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrimitivaResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoResponse")]
        List<ServicioLematizacion.InfoPrefijo> ConsultaPrefijo(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoResponse")]
        System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCod", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCodResponse")]
        ServicioLematizacion.InfoPrefijo ConsultaPrefijoCod(int idPrefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCod", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCodResponse")]
        System.Threading.Tasks.Task<ServicioLematizacion.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexion", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionResponse")]
        ServicioLematizacion.InfoFlexion ConsultaFlexion(int idFlexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexion", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionResponse")]
        System.Threading.Tasks.Task<ServicioLematizacion.InfoFlexion> ConsultaFlexionAsync(int idFlexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCategoria", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCategoriaResponse")]
        ServicioLematizacion.InfoCategoria ConsultaCategoria(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCategoria", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCategoriaResponse")]
        System.Threading.Tasks.Task<ServicioLematizacion.InfoCategoria> ConsultaCategoriaAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexiones", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexionesResponse")]
        System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoFlexion> ConsultaCodigosFlexiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexiones", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoFlexion>> ConsultaCodigosFlexionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategorias", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategoriasResponse")]
        System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoCategoria> ConsultaCodigosCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategorias", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoCategoria>> ConsultaCodigosCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServicioLematizacionChannel : ServicioLematizacion.IServicioLematizacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServicioLematizacionClient : System.ServiceModel.ClientBase<ServicioLematizacion.IServicioLematizacion>, ServicioLematizacion.IServicioLematizacion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioLematizacionClient() : 
                base(ServicioLematizacionClient.GetDefaultBinding(), ServicioLematizacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioLematizacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioLematizacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioLematizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool EsVerbo(string verbo)
        {
            return base.Channel.EsVerbo(verbo);
        }
        
        public System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo)
        {
            return base.Channel.EsVerboAsync(verbo);
        }
        
        public List<ServicioLematizacion.Reconocimiento> Reconocer(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.Reconocer(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerAsync(palabra, idioma, multiPref);
        }
        
        public List<ServicioLematizacion.ParamtextFrase> ReconocerTextoPorFrases(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerTextoPorFrases(frases, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.ParamtextFrase>> ReconocerTextoPorFrasesAsync(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerTextoPorFrasesAsync(frases, idioma, multiPref);
        }
        
        public List<ServicioLematizacion.ParamtextFrase> ReconocerLinguakit(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerLinguakit(frases, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.ParamtextFrase>> ReconocerLinguakitAsync(List<ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerLinguakitAsync(frases, idioma, multiPref);
        }
        
        public List<ServicioLematizacion.Reconocimiento> ReconocerFlexible(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerFlexible(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerFlexibleAsync(palabra, idioma, multiPref);
        }
        
        public List<ServicioLematizacion.Reconocimiento> ReconocerVerbo(string verbo, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerVerbo(verbo, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref)
        {
            return base.Channel.ReconocerVerboAsync(verbo, idioma, multiPref);
        }
        
        public ServicioLematizacion.InfoCanonica ConsultaCanonica(int idFormaCanonica)
        {
            return base.Channel.ConsultaCanonica(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizacion.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica)
        {
            return base.Channel.ConsultaCanonicaAsync(idFormaCanonica);
        }
        
        public List<ServicioLematizacion.InfoPalabra> ConsultaPalabra(string palabra)
        {
            return base.Channel.ConsultaPalabra(palabra);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPalabra>> ConsultaPalabraAsync(string palabra)
        {
            return base.Channel.ConsultaPalabraAsync(palabra);
        }
        
        public List<string> PalabrasNoEncontradas(List<string> listaPalabras)
        {
            return base.Channel.PalabrasNoEncontradas(listaPalabras);
        }
        
        public System.Threading.Tasks.Task<List<string>> PalabrasNoEncontradasAsync(List<string> listaPalabras)
        {
            return base.Channel.PalabrasNoEncontradasAsync(listaPalabras);
        }
        
        public List<ServicioLematizacion.InfoFlexionador> ConsultaFlexionador(int idFormaCanonica)
        {
            return base.Channel.ConsultaFlexionador(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica)
        {
            return base.Channel.ConsultaFlexionadorAsync(idFormaCanonica);
        }
        
        public List<ServicioLematizacion.InfoVerbo> ConsultaVerbo(string verbo)
        {
            return base.Channel.ConsultaVerbo(verbo);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.InfoVerbo>> ConsultaVerboAsync(string verbo)
        {
            return base.Channel.ConsultaVerboAsync(verbo);
        }
        
        public List<ServicioLematizacion.InfoPrimitiva> ConsultaPrimitiva(string palabra)
        {
            return base.Channel.ConsultaPrimitiva(palabra);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra)
        {
            return base.Channel.ConsultaPrimitivaAsync(palabra);
        }
        
        public List<ServicioLematizacion.InfoPrefijo> ConsultaPrefijo(string prefijo)
        {
            return base.Channel.ConsultaPrefijo(prefijo);
        }
        
        public System.Threading.Tasks.Task<List<ServicioLematizacion.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo)
        {
            return base.Channel.ConsultaPrefijoAsync(prefijo);
        }
        
        public ServicioLematizacion.InfoPrefijo ConsultaPrefijoCod(int idPrefijo)
        {
            return base.Channel.ConsultaPrefijoCod(idPrefijo);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizacion.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo)
        {
            return base.Channel.ConsultaPrefijoCodAsync(idPrefijo);
        }
        
        public ServicioLematizacion.InfoFlexion ConsultaFlexion(int idFlexion)
        {
            return base.Channel.ConsultaFlexion(idFlexion);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizacion.InfoFlexion> ConsultaFlexionAsync(int idFlexion)
        {
            return base.Channel.ConsultaFlexionAsync(idFlexion);
        }
        
        public ServicioLematizacion.InfoCategoria ConsultaCategoria(int idCategoria)
        {
            return base.Channel.ConsultaCategoria(idCategoria);
        }
        
        public System.Threading.Tasks.Task<ServicioLematizacion.InfoCategoria> ConsultaCategoriaAsync(int idCategoria)
        {
            return base.Channel.ConsultaCategoriaAsync(idCategoria);
        }
        
        public System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoFlexion> ConsultaCodigosFlexiones()
        {
            return base.Channel.ConsultaCodigosFlexiones();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoFlexion>> ConsultaCodigosFlexionesAsync()
        {
            return base.Channel.ConsultaCodigosFlexionesAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoCategoria> ConsultaCodigosCategorias()
        {
            return base.Channel.ConsultaCodigosCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, ServicioLematizacion.InfoCategoria>> ConsultaCodigosCategoriasAsync()
        {
            return base.Channel.ConsultaCodigosCategoriasAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.TransferMode = System.ServiceModel.TransferMode.Streamed;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion))
            {
                return new System.ServiceModel.EndpointAddress("https://appstip.iatext.ulpgc.es/ServicioLematizacionWCF/ServicioLematizacion.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioLematizacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioLematizacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IServicioLematizacion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IServicioLematizacion,
        }
    }
}
